config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views
from map.views import map_views
from prescription.views import pre_views
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),  # '/' 에 해당되는 path
    path('map/', include('map.urls')),
    path('prescription/', include('prescription.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

map/urls.py
from django.urls import path

from .views import map_views

app_name = 'map'

urlpatterns = [
    # map_views.py
    path('', map_views.map, name='map'),
]

map/models.py
from django.db import models


# Create your models here.

class Hospital(models.Model):
    encoded_id = models.CharField(max_length=50)
    hospital_name = models.CharField(max_length=50)
    type_code = models.IntegerField()
    type_name = models.CharField(max_length=50)
    city_code = models.IntegerField()
    city_name = models.CharField(max_length=50)
    district_code = models.IntegerField()
    district_name = models.CharField(max_length=50)
    town = models.CharField(max_length=50)
    zipcode = models.IntegerField()
    address = models.CharField(max_length=50)
    phone = models.CharField(max_length=50)
    url = models.CharField(max_length=50)
    foundation_date = models.FloatField()
    longitude = models.FloatField()
    latitude = models.FloatField()
    total_doctor_num = models.IntegerField()
    doctor_num = models.IntegerField()
    intern_num = models.IntegerField()
    resi_num = models.IntegerField()
    board_num = models.IntegerField()

    def __str__(self):
        return self.encoded_id


class Device(models.Model):
    encoded_id = models.CharField(max_length=50)
    hospital_name = models.CharField(max_length=50)
    device_code = models.IntegerField()
    device_name = models.CharField(max_length=50)
    device_num = models.IntegerField()

    def __str__(self):
        return self.encoded_id

map/views.py
from django.shortcuts import render

# Create your views here.

map/views/map_views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.db.models import Q, Count

import json

from ..models import Hospital, Device


def map(request):
    """
    지도 검색창 출력
    """
    # 입력 파라미터
    kw = request.GET.get('kw', '')  # 검색어
    hospital = Hospital.objects.all()
    device = Device.objects.all()

    # 검색
    if kw:
        hospital = hospital.filter(
            Q(hospital_name__icontains=kw)
        ).distinct()

        # device = device.filter(
        #     Q(hospital_name__icontains=kw)
        # ).distinct()
        # temp_device = device[0]  # 확인: 각 병원의 디바이스 하나만 불러짐 (수정 요)

        temp_name = hospital[0]  # 검색 후 첫번째 병원 - todo
        hospital_id = temp_name.encoded_id
        device = device.filter(encoded_id=hospital_id)  # list of devices for each hospital

        # device_dict = dict()
        # for d in device:  # d.device_code, d.device_name, d.device_num
        #     device_dict[d.device_code] = [d.device_name, d.device_num]

        device_code_list = []
        device_name_list = []
        device_num_list = []
        for d in device:
            device_code_list.append(d.device_code)
            device_name_list.append(d.device_name)
            device_num_list.append(d.device_num)

        context = {
            'encoded_id': temp_name.encoded_id,
            'zipcode': temp_name.zipcode,
            'address': temp_name.address,
            'phone': temp_name.phone,
            'url': temp_name.url,
            'hospital_name': temp_name.hospital_name,
            'latitude': temp_name.latitude,
            'longitude': temp_name.longitude,
            'total_doctor_num': temp_name.total_doctor_num,
            'doctor_num': temp_name.doctor_num,
            'intern_num': temp_name.intern_num,
            'resi_num': temp_name.resi_num,
            'board_num': temp_name.board_num,
            'device_code': device_code_list,
            'device_name': device_name_list,
            'device_num': device_num_list,
            'kw': kw}

        # context = {
        #     'encoded_id': temp_name.encoded_id,
        #     'zipcode': temp_name.zipcode,
        #     'address': temp_name.address,
        #     'phone': temp_name.phone,
        #     'url': temp_name.url,
        #     'hospital_name': temp_name.hospital_name,
        #     'latitude': temp_name.latitude,
        #     'longitude': temp_name.longitude,
        #     'total_doctor_num': temp_name.total_doctor_num,
        #     'doctor_num': temp_name.doctor_num,
        #     'intern_num': temp_name.intern_num,
        #     'resi_num': temp_name.resi_num,
        #     'board_num': temp_name.board_num,
        #     'device_name': temp_device.device_name,
        #     'device_num': temp_device.device_num,
        #     'kw': kw}


    else:
        temp_name = hospital.filter(
            Q(hospital_name__icontains='카이스트')
        ).distinct()
        context = {
            'hospital_name': '카이스트병원',
            'latitude': 36.371613355884065,
            'longitude': 127.36190815365813,
            'kw': kw}

    context_json = json.dumps(context)

    return render(request, 'map/map_search.html', {'context_json': context_json})

templates/map/map_home.html
{% extends 'map_base.html' %}
{% block content %}
<div class="container">
    <div class="jumbotron">
        <h1>병원 검색</h1>
        <p>병원을 검색해주세요.</p>
    </div>
</div>
<div class="'container">
    <div class="row justify-content-around">
        <div class="col-4 input-group">
            <input type="text" class="form-control kw" value="{{ kw|default_if_none:'' }}">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
            </div>
        </div>
    </div>
</div>

<form id="searchForm" method="get" action="{% url 'map:map' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
</form>
<!--데이: {{ context_json }}-->

{% endblock %}


{% block script %}


<script type='text/javascript'>
$(document).ready(function(){
    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#searchForm").submit();
    });
});
</script>

<div class="row justify-content-around">
<div id="map" style="width:75%;height:1000px"></div> <!-- 지도를 표시할 div 입니다 -->

<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=0e745bdef31ee08f01b4b787b9dea8cb"></script>
<script>

// custom codes
var data = JSON.parse("{{ context_json|escapejs }}")

var map_address = format("https://map.kakao.com/link/map/{0},{1},{2}",
    data['hospital_name'], data['latitude'], data['longitude'])

var map_route = format("https://map.kakao.com/link/to/{0},{1},{2}",
    data['hospital_name'], data['latitude'], data['longitude'])

function format() { var args = Array.prototype.slice.call (arguments, 1); return arguments[0].replace (/\{(\d+)\}/g, function (match, index) { return args[index]; }); }


///// Map code starts /////
var mapContainer = document.getElementById('map'), // 지도를 표시할 div
    mapOption = {
        center: new kakao.maps.LatLng(data['latitude'], data['longitude']), // 지도의 중심좌표
        level: 3 // 지도의 확대 레벨
    };

// 지도를 표시할 div와  지도 옵션으로  지도를 생성합니다
var map = new kakao.maps.Map(mapContainer, mapOption);


// 커스텀 오버레이에 표시할 내용입니다
// HTML 문자열 또는 Dom Element 입니다
var content = '<div class="overlay_info">';
content += '    <a href={0} target="_blank"><strong>{1}</strong></a>';
content += '    <div class="desc">';
content += '        <span>' +
    '<li>진료과목: </li>' +
    '<li>의사 수: {2}</li>' +
    '<li>전문의 수: {3}</li>' +
    '<li>의료장비 수</li>' +
    '</span>';
content += '<div class="shadowbox"><br><a href={4} style="color:blue" target="_blank">큰지도보기</a></div>'

content += '    </div>';
content += '</div>';

var content = format(content,
    data['url'],
    data['hospital_name'],
    data['total_doctor_num'],
    data['board_num'],
    map_address
)

// var iwContent = '<div style="padding:5px;">Hello World! ' +
//     '<br><a href="https://map.kakao.com/link/map/Hello World!,33.450701,126.570667" style="color:blue" target="_blank">큰지도보기</a> <a href="https://map.kakao.com/link/to/Hello World!,33.450701,126.570667" style="color:blue" target="_blank">길찾기</a></div>', // 인포윈도우에 표출될 내용으로 HTML 문자열이나 document element가 가능합니다

// 커스텀 오버레이가 표시될 위치입니다
var position =  new kakao.maps.LatLng(data['latitude'], data['longitude']);

// 커스텀 오버레이를 생성합니다
var mapCustomOverlay = new kakao.maps.CustomOverlay({
    position: position,
    content: content,
    xAnchor: 0.5, // 커스텀 오버레이의 x축 위치입니다. 1에 가까울수록 왼쪽에 위치합니다. 기본값은 0.5 입니다
    yAnchor: 1.1 // 커스텀 오버레이의 y축 위치입니다. 1에 가까울수록 위쪽에 위치합니다. 기본값은 0.5 입니다
});

// 커스텀 오버레이를 지도에 표시합니다
mapCustomOverlay.setMap(map)

</script>
</div>
{% endblock %}

templates/map/map_search.html
{% extends 'map_clickable.html' %}
{% block content %}
<div class="container">
    <div class="jumbotron">
        <h1>병원 검색</h1>
        <p>병원을 검색해주세요.</p>
    </div>
</div>
<div class="'container">
    <div class="row justify-content-around">
        <div class="col-4 input-group">
            <input type="text" class="form-control kw" value="{{ kw|default_if_none:'' }}">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
            </div>
        </div>
    </div>
</div>

<form id="searchForm" method="get" action="{% url 'map:map' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
</form>
<!--데이터: {{ context_json }}-->

{% endblock %}


{% block script %}


<script type='text/javascript'>
$(document).ready(function(){
    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#searchForm").submit();
    });
});
</script>

<br><br>

<div class="row justify-content-around">
<div id="map" style="width:75%;height:1000px;"></div>

<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=0e745bdef31ee08f01b4b787b9dea8cb"></script>
<script>

// custom codes
var data = JSON.parse("{{ context_json|escapejs }}")

var map_address = format("https://map.kakao.com/link/map/{0},{1},{2}",
    data['hospital_name'], data['latitude'], data['longitude'])

var map_route = format("https://map.kakao.com/link/to/{0},{1},{2}",
    data['hospital_name'], data['latitude'], data['longitude'])

function format() { var args = Array.prototype.slice.call (arguments, 1); return arguments[0].replace (/\{(\d+)\}/g, function (match, index) { return args[index]; }); }

// Map code starts
var mapContainer = document.getElementById('map'), // 지도의 중심좌표
    mapOption = {
        center: new kakao.maps.LatLng(data['latitude'], data['longitude']), // 지도의 중심좌표
        level: 3 // 지도의 확대 레벨
    };

var map = new kakao.maps.Map(mapContainer, mapOption); // 지도를 생성합니다

// 지도에 마커를 표시합니다
var marker = new kakao.maps.Marker({
    map: map,
    position: new kakao.maps.LatLng(data['latitude'], data['longitude'])
});

// 커스텀 오버레이에 표시할 컨텐츠 입니다
// 커스텀 오버레이는 아래와 같이 사용자가 자유롭게 컨텐츠를 구성하고 이벤트를 제어할 수 있기 때문에
// 별도의 이벤트 메소드를 제공하지 않습니다
var content = '<div class="wrap">' +
            '    <div class="info">' +
            '        <div class="title">' +
            '            {0}' +
            '            <div class="close" onclick="closeOverlay()" title="닫기"></div>' +
            '        </div>' +
            '        <div class="body">' +
            '            <div class="desc">' +
            '                <div class="contents"><li>진료과목: </li></div>' +
            '                <div class="contents"><li>의사 수: {1}</li></div>' +
            '                <div class="contents"><li>전문의 수: {2}</li></div>' +
            '                <div class="contents"><li>보유 장비명: {7}</li></div>' +
            '                <div class="contents"><li>보유 장비수: {8}</li></div>' +
            '                <br>' +

            '                <div class="ellipsis">{3}</div>' +
            '                <div class="jibun ellipsis">(Phone)  {4}   (우) {5}</div>';
if (data['url'] !== null){
    content += '             <div><a href={6} target="_blank" class="link">홈페이지</a></div>'
}

content += '            </div>' +
            '        </div>' +
            '    </div>' +
            '</div>';


var content = format(content,
    data['hospital_name'],
    data['total_doctor_num'],
    data['board_num'],
    data['address'],
    data['phone'],
    data['zipcode'],
    data['url'],
    data['device_code'].length,
    data['device_num']
)

// 마커 위에 커스텀오버레이를 표시합니다
// 마커를 중심으로 커스텀 오버레이를 표시하기위해 CSS를 이용해 위치를 설정했습니다
var overlay = new kakao.maps.CustomOverlay({
    content: content,
    map: map,
    position: marker.getPosition()
});

// 마커를 클릭했을 때 커스텀 오버레이를 표시합니다
kakao.maps.event.addListener(marker, 'click', function() {
    overlay.setMap(map);
});

// 커스텀 오버레이를 닫기 위해 호출되는 함수입니다
function closeOverlay() {
    overlay.setMap(null);
}
</script>
</div>
</div>

{% endblock %}